ARG PYTHON_VERSION={{ python_version }}
ARG DEBIAN_VERSION=bookworm
ARG BASE_IMAGE=python:${PYTHON_VERSION}-slim-${DEBIAN_VERSION}

ARG USERNAME=appuser
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG PROJECT_WORKDIR=/opt/{{ project_slug }}

# * Base python image including uv
FROM ${BASE_IMAGE} AS base

ARG PROJECT_WORKDIR
ARG USERNAME
ARG USER_UID
ARG USER_GID

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH="/home/${USERNAME}/.local/bin/:$PATH"

# Install system dependencies
RUN apt-get update --fix-missing \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bzip2 ca-certificates curl git wget zip \
    procps net-tools iputils-ping vim iproute2 dnsutils lsof netcat-openbsd \
    build-essential cmake pkg-config \
 && DEBIAN_FRONTEND=noninteractive apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Create non-root user without initializing homedir
RUN groupadd -r -g ${USER_GID} ${USERNAME} \
 && useradd --no-log-init -r -u ${USER_UID} -g ${USER_GID} ${USERNAME} \
 && mkdir -p /home/${USERNAME} \
 && mkdir -p /home/${USERNAME}/.local/bin \
 && mkdir -p ${PROJECT_WORKDIR} \
 && chown -R ${USER_UID}:${USER_GID} /home/${USERNAME}

USER ${USERNAME}

# Download the latest uv installer and install uv
RUN curl -L https://astral.sh/uv/install.sh -o /tmp/uv-installer.sh \
 && sh /tmp/uv-installer.sh && rm /tmp/uv-installer.sh

WORKDIR ${PROJECT_WORKDIR}
